Repository kokonut27/zsq, pull requests merged in 2022-01, with the labels that each got.

#6 Add alias instructions
  README.md
Labels: documentation, enhancement, in progress, High priority

#7 Improve alias instructions
  README.md
Labels: documentation, enhancement, Medium priority

#8 'Refactored by Sourcery'
  zsq/__main__.py
Labels: documentation, enhancement, in progress, Medium priority
